name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file DockerfileFrps --tag my-image-name:$(date +%s)
    - name: Build the Docker image2
      run: docker build . -f DockerfileFrps --build-arg FRP_VERSION="0.71.0" -t mtjo/frp:frps-v0.71.0     
